// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agro-newscan/Precise.tsx": () => import("../components/mockups/agro-newscan/Precise.tsx"),
  "./components/mockups/agro-newscan/Warm.tsx": () => import("../components/mockups/agro-newscan/Warm.tsx"),
  "./components/mockups/agro-landing/Bento.tsx": () => import("../components/mockups/agro-landing/Bento.tsx"),
  "./components/mockups/agro-landing/Conversation.tsx": () => import("../components/mockups/agro-landing/Conversation.tsx"),
  "./components/mockups/agro-landing/Editorial.tsx": () => import("../components/mockups/agro-landing/Editorial.tsx"),
  "./components/mockups/agro-landing/FieldMap.tsx": () => import("../components/mockups/agro-landing/FieldMap.tsx"),
  "./components/mockups/agro-landing/LiveScan.tsx": () => import("../components/mockups/agro-landing/LiveScan.tsx"),
  "./components/mockups/agro-landing/Split.tsx": () => import("../components/mockups/agro-landing/Split.tsx")
};
