// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agro-landing/Bento.tsx": () => import("../components/mockups/agro-landing/Bento.tsx"),
  "./components/mockups/agro-landing/Editorial.tsx": () => import("../components/mockups/agro-landing/Editorial.tsx"),
  "./components/mockups/agro-landing/Split.tsx": () => import("../components/mockups/agro-landing/Split.tsx")
};
